### ISSUE TITLE
Please add an OSI-approved LICENSE

### ISSUE THREAD

**Issue by bgrant0607** [redhat-developer/opencompose-old#5]
Ideally Apache 2.

**Comment by pradeepto** [comment]
@bgrant0607 Will do. But since the original intention of this repository was to have the spec document in it. Should the license be Apache 2 or something else? @pmuir Any thoughts?

**Comment by pmuir** [comment]
+1 for Apache 2

**Comment by pradeepto** [comment]
Thanks. I will get this done first thing tomorrow morning.

**Comment by bgrant0607** [comment]
@pradeepto We prefer Apache 2, also, thanks.

**Comment by pradeepto** [comment]
Added the license. Closing this issue.
